"""The project-local app launcher, its project-root link, and its lifecycle.

The launcher is machine-local: it brings the app up for one project with that
project's runtime root and a port it chooses, records the pid and port it served,
and stops the whole process group so nothing it started is left running.

Every path this module names carries `research-rag`, because the MCP server this
product was seeded from generates its launcher beside it. Two products sharing one
pid file would let each stop the other's process.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from .config import ResearchConfig

LAUNCHER_DIRECTORY = "bin"
LAUNCHER_NAME = "open-research-rag-ui.sh"
LINK_NAME = "open-research-rag-ui.sh"
LINK_TARGET = f".research-rag/{LAUNCHER_DIRECTORY}/{LAUNCHER_NAME}"
DEFAULT_UI_PORT = 5051
# The one console command this product installs. The launcher runs its `serve`
# subcommand, because `ui` is the subcommand that starts the launcher.
UI_COMMAND = "research-rag"
SERVE_COMMAND = "serve"


def default_ui_command() -> str:
    """The UI command to embed, preferring the running environment.

    A launcher runs from a user shell, where the console script a server was installed
    with is usually absent from `PATH`, so an absolute sibling of the running
    interpreter wins over the bare name.
    """

    if sys.executable:
        sibling = Path(sys.executable).parent / UI_COMMAND
        if sibling.is_file() and os.access(sibling, os.X_OK):
            return str(sibling)
    return shutil.which(UI_COMMAND) or UI_COMMAND


_TEMPLATE = """#!/bin/sh
# Generated by research-rag for the @PROJECT_NAME@ project.
#
#   open-research-rag-ui.sh                 start the app
#   open-research-rag-ui.sh --open          start it and open a browser
#   open-research-rag-ui.sh --stop          stop it, and what it started
#   open-research-rag-ui.sh --port NUMBER   start it on a different port
#   open-research-rag-ui.sh --help          show this text
#
# Machine-local by design: the project's own .gitignore should keep it out of Git.
set -eu

PROJECT_ROOT="@PROJECT_ROOT@"
STATE_ROOT="@STATE_ROOT@"
RUNTIME_ROOT="@RUNTIME_ROOT@"
PORT=@PORT@
UI_COMMAND="@UI_COMMAND@"
# Every global option comes first and the subcommand's own options come after
# it, because argparse reads them in front of and behind the command they belong
# to, not anywhere on the line.

PID_FILE="$STATE_ROOT/research-rag-ui.pid"
PORT_FILE="$STATE_ROOT/research-rag-ui.port"
LOG_FILE="$STATE_ROOT/logs/research-rag-ui.log"
LOCK_DIR="$STATE_ROOT/research-rag-ui.lock"
# 0.25s steps: how long a launcher waits for another one that is choosing a port.
LOCK_WAIT=40
# Attempts at finding a port that this project's UI can bind.
LAUNCH_ATTEMPTS=5
# 0.25s steps a started UI gets to answer on its port before the attempt fails.
READY_WAIT=80
# The interpreter beside the UI command speaks Python; the port scan needs it.
PYTHON="$(dirname "$UI_COMMAND")/python3"
[ -x "$PYTHON" ] || PYTHON=python3
OPEN_BROWSER=0
PORT_EXPLICIT=0

usage() {
  cat <<'TEXT'
Usage: open-research-rag-ui.sh [--open] [--stop] [--port NUMBER] [--help]

  (no option)    start the app for this project and print its URL
  --open         start it and open a browser
  --stop         stop it, and everything it started
  --port NUMBER  start it on a different port
  --help         show this text

Without --port the launcher starts on the first free port at or above the one it
was generated with, so two projects never serve from the same port.
TEXT
}

running_pid() {
  [ -f "$PID_FILE" ] || return 1
  pid=$(cat "$PID_FILE" 2>/dev/null || true)
  [ -n "$pid" ] || return 1
  kill -0 "$pid" 2>/dev/null || return 1
  printf '%s' "$pid"
}

serving_port() {
  cat "$PORT_FILE" 2>/dev/null || printf '%s' "$PORT"
}

free_port() {
  # The first free port at or above the requested one. A second project's launcher
  # must never take a port another project's UI is already serving on, because
  # opening that URL would show the wrong project.
  "$PYTHON" -c "import socket, sys
for candidate in range(int(sys.argv[1]), int(sys.argv[1]) + 100):
    try:
        with socket.socket() as probe:
            probe.bind(('127.0.0.1', candidate))
        print(candidate)
        break
    except OSError:
        continue" "$1" 2>/dev/null || printf '%s' "$1"
}

open_url() {
  if command -v xdg-open >/dev/null 2>&1; then
    xdg-open "http://127.0.0.1:$PORT" >/dev/null 2>&1 || true
  else
    echo "Open http://127.0.0.1:$PORT in your browser."
  fi
}

take_lock() {
  # mkdir is atomic, so two launchers can never both be choosing a port. A lock
  # whose writer is gone is not a claim either: that is what a killed launcher
  # leaves behind.
  waited=0
  while ! mkdir "$LOCK_DIR" 2>/dev/null; do
    owner=$(cat "$LOCK_DIR/pid" 2>/dev/null || true)
    if [ -n "$owner" ] && ! kill -0 "$owner" 2>/dev/null; then
      rm -rf "$LOCK_DIR"
      continue
    fi
    if [ "$waited" -ge "$LOCK_WAIT" ]; then
      echo "Another launcher is choosing a port for this project; try again." >&2
      exit 1
    fi
    sleep 0.25
    waited=$((waited + 1))
  done
  printf '%s' "$$" > "$LOCK_DIR/pid"
  trap 'rm -rf "$LOCK_DIR"' EXIT INT TERM
}

ui_serves_port() {
  # True when PORT is served by the process this launcher started, or by one of
  # its children. Another project's UI answering on the same port must not count,
  # and a UI that lost the bind is on its way out. Exit 2 means there is no /proc
  # to inspect, and the caller falls back to waiting on the process alone.
  "$PYTHON" -c "
import os, sys

pid, port = int(sys.argv[1]), int(sys.argv[2])
children = {}
for entry in os.listdir('/proc'):
    if not entry.isdigit():
        continue
    try:
        with open('/proc/%s/stat' % entry) as handle:
            fields = handle.read().rsplit(') ', 1)[-1].split()
    except OSError:
        continue
    children.setdefault(int(fields[1]), []).append(int(entry))

tree, queue = {pid}, [pid]
while queue:
    for child in children.get(queue.pop(), []):
        if child not in tree:
            tree.add(child)
            queue.append(child)

inodes = set()
for member in tree:
    try:
        names = os.listdir('/proc/%d/fd' % member)
    except OSError:
        continue
    for name in names:
        try:
            target = os.readlink('/proc/%d/fd/%s' % (member, name))
        except OSError:
            continue
        if target.startswith('socket:['):
            inodes.add(target[8:-1])

try:
    handle = open('/proc/net/tcp')
except OSError:
    sys.exit(2)
want = ':%04X' % port
found = False
if inodes:
    with handle:
        next(handle, None)
        for line in handle:
            fields = line.split()
            if (
                len(fields) > 9
                and fields[3] == '0A'
                and fields[1].endswith(want)
                and fields[9] in inodes
            ):
                found = True
                break
sys.exit(0 if found else 1)" "$1" "$2" 2>/dev/null
}

launch() {
  # One attempt on the current PORT. The child leads its own session, so a later
  # --stop can signal the UI and everything the UI starts below it.
  mkdir -p "$STATE_ROOT/logs"
  if [ -n "$RUNTIME_ROOT" ]; then
    if command -v setsid >/dev/null 2>&1; then
      setsid "$UI_COMMAND" --project-root "$PROJECT_ROOT" \\
        --runtime-root "$RUNTIME_ROOT" @SERVE@ --port "$PORT" >>"$LOG_FILE" 2>&1 &
    else
      "$UI_COMMAND" --project-root "$PROJECT_ROOT" \\
        --runtime-root "$RUNTIME_ROOT" @SERVE@ --port "$PORT" >>"$LOG_FILE" 2>&1 &
    fi
  else
    if command -v setsid >/dev/null 2>&1; then
      setsid "$UI_COMMAND" --project-root "$PROJECT_ROOT" \\
        @SERVE@ --port "$PORT" >>"$LOG_FILE" 2>&1 &
    else
      "$UI_COMMAND" --project-root "$PROJECT_ROOT" \\
        @SERVE@ --port "$PORT" >>"$LOG_FILE" 2>&1 &
    fi
  fi
  CANDIDATE=$!
  # Probing for a free port and binding it are two steps, so another project's
  # launcher can take this port in between and leave this UI dying with a bind
  # error. Waiting until the port is served by *this* process is what makes the
  # recorded pid and port trustworthy, and it keeps the lock held until the
  # answer is real so the next launcher's probe is honest.
  waited=0
  while [ "$waited" -lt "$READY_WAIT" ]; do
    if ! kill -0 "$CANDIDATE" 2>/dev/null; then
      return 1
    fi
    served=0
    ui_serves_port "$CANDIDATE" "$PORT" || served=$?
    if [ "$served" = "0" ]; then
      return 0
    fi
    if [ "$served" = "2" ]; then
      # Nothing to inspect, so a process that has survived its startup is the
      # only evidence available.
      sleep 2
      kill -0 "$CANDIDATE" 2>/dev/null && return 0
      return 1
    fi
    sleep 0.25
    waited=$((waited + 1))
  done
  # Nothing of ours serves this port, so the attempt is over and the process that
  # did not serve it must not be left running.
  kill -TERM "$CANDIDATE" 2>/dev/null || true
  return 1
}

start() {
  if pid=$(running_pid); then
    echo "The app is already running for this project (pid $pid)."
    echo "URL: http://127.0.0.1:$(serving_port)"
  else
    take_lock
    attempts=0
    started=0
    while [ "$attempts" -lt "$LAUNCH_ATTEMPTS" ]; do
      attempts=$((attempts + 1))
      if [ "$PORT_EXPLICIT" = "0" ]; then
        PORT="$(free_port "$PORT")"
      fi
      if launch; then
        started=1
        break
      fi
      # The UI exited straight away. Probing for a free port and binding it are
      # two steps, so another process can take the port in between and leave this
      # attempt as the loser: take the next port rather than leave the project
      # without a UI. An explicit --port is the caller's choice, so it is final.
      if [ "$PORT_EXPLICIT" = "1" ]; then
        break
      fi
      PORT=$((PORT + 1))
    done
    if [ "$started" != "1" ]; then
      rm -rf "$LOCK_DIR"
      echo "The app did not stay up; read $LOG_FILE" >&2
      exit 1
    fi
    # Recorded only once the UI is known to be running, so a failed attempt
    # cannot leave a pid or a port file naming something that is not there.
    printf '%s' "$PORT" > "$PORT_FILE"
    printf '%s' "$CANDIDATE" > "$PID_FILE"
    rm -rf "$LOCK_DIR"
    echo "Started the app for this project (pid $CANDIDATE)."
    echo "URL: http://127.0.0.1:$PORT"
    echo "Log: $LOG_FILE"
  fi
  if [ "$OPEN_BROWSER" = "1" ]; then
    open_url
  fi
}

owns_project() {
  # Without /proc to read, the pid file is all there is to go on.
  [ -r "/proc/$1/cmdline" ] || return 0
  tr '\\0' ' ' < "/proc/$1/cmdline" | grep -F -- "$PROJECT_ROOT" >/dev/null 2>&1
}

sweep_processes() {
  # A build busy in a long phase does not read its parent until the phase returns,
  # so it can outlive the workspace that started it. The CLI's own sweep names
  # this project and is a no-op when nothing is left; a missing entry point must
  # not fail a stop.
  SWEEP="$UI_COMMAND"
  [ -x "$SWEEP" ] || return 0
  "$SWEEP" --project-root "$PROJECT_ROOT" stop --servers >>"$LOG_FILE" 2>&1 || true
}

stop() {
  if ! pid=$(running_pid); then
    rm -f "$PID_FILE"
    echo "No app is running for this project."
    return 0
  fi
  if ! owns_project "$pid"; then
    # A pid file outlives its process and the number can be reused, and a port
    # file can name another project's port when two launchers raced. Neither is a
    # reason to signal a process that is not this project's workspace.
    rm -f "$PID_FILE" "$PORT_FILE"
    echo "Pid $pid is not this project's app; left it alone." >&2
    return 0
  fi
  # The workspace starts its UltraRAG gateway below it, so stop the whole process
  # group rather than only the launcher's own child. A build that was still busy
  # when the workspace died is swept separately afterwards.
  kill -TERM "-$pid" 2>/dev/null || kill -TERM "$pid" 2>/dev/null || true
  waited=0
  while kill -0 "$pid" 2>/dev/null && [ "$waited" -lt 20 ]; do
    sleep 0.25
    waited=$((waited + 1))
  done
  if kill -0 "$pid" 2>/dev/null; then
    kill -KILL "-$pid" 2>/dev/null || kill -KILL "$pid" 2>/dev/null || true
  fi
  rm -f "$PID_FILE"
  sweep_processes
  echo "Stopped the app for this project (pid $pid)."
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --open) OPEN_BROWSER=1 ;;
    --stop) stop; exit 0 ;;
    --port)
      [ "$#" -ge 2 ] || { echo "--port needs a number" >&2; exit 2; }
      PORT="$2"
      PORT_EXPLICIT=1
      shift
      ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

if [ ! -d "$PROJECT_ROOT" ]; then
  echo "Project root is missing: $PROJECT_ROOT" >&2
  exit 1
fi
start
"""


def launcher_path(portable_root: Path) -> Path:
    return portable_root / LAUNCHER_DIRECTORY / LAUNCHER_NAME


def link_path(project_root: Path) -> Path:
    return project_root / LINK_NAME


def launcher_script(
    *,
    project_root: Path,
    state_root: Path,
    project_name: str,
    port: int = DEFAULT_UI_PORT,
    runtime_root: Path | None = None,
    ui_command: str | None = None,
) -> str:
    return (
        _TEMPLATE.replace("@SERVE@", SERVE_COMMAND)
        .replace("@PROJECT_NAME@", project_name)
        .replace("@PROJECT_ROOT@", str(project_root))
        .replace("@STATE_ROOT@", str(state_root))
        .replace("@RUNTIME_ROOT@", str(runtime_root) if runtime_root else "")
        .replace("@PORT@", str(port))
        .replace("@UI_COMMAND@", ui_command or default_ui_command())
    )


def _link_state(link: Path) -> str:
    if link.is_symlink():
        return "linked" if os.readlink(link) == LINK_TARGET else "foreign_link"
    if link.exists():
        return "foreign_file"
    return "absent"


def ensure_ui_launcher(
    *,
    project_root: Path,
    portable_root: Path,
    state_root: Path,
    project_name: str,
    port: int = DEFAULT_UI_PORT,
    runtime_root: Path | None = None,
    ui_command: str | None = None,
) -> dict[str, Any]:
    """Create the launcher and its project-root link when absent.

    An existing entry is never overwritten, so a user edit survives. Failures are
    reported rather than raised, because the launcher must never stop the server from
    starting.
    """

    script = launcher_path(portable_root)
    link = link_path(project_root)
    script_state = "present"
    note: str | None = None
    try:
        script.parent.mkdir(parents=True, exist_ok=True)
        if not script.exists():
            temporary = script.with_name(f".{script.name}.tmp")
            temporary.write_text(
                launcher_script(
                    project_root=project_root,
                    state_root=state_root,
                    project_name=project_name,
                    port=port,
                    runtime_root=runtime_root,
                    ui_command=ui_command,
                ),
                encoding="utf-8",
                newline="\n",
            )
            temporary.chmod(0o755)
            os.replace(temporary, script)
            script_state = "created"
    except OSError as exc:
        return {
            "script_path": str(script),
            "link_path": str(link),
            "link_target": LINK_TARGET,
            "script_state": "unavailable",
            "link_state": _link_state(link),
            "note": str(exc),
        }
    link_state = _link_state(link)
    try:
        if link_state == "absent":
            link.symlink_to(LINK_TARGET)
            link_state = "linked"
        elif link_state != "linked":
            note = (
                f"The project root already has a {LINK_NAME} this app did not "
                "create; it was left untouched."
            )
    except OSError as exc:
        link_state = "unavailable"
        note = str(exc)
    return {
        "script_path": str(script),
        "link_path": str(link),
        "link_target": LINK_TARGET,
        "script_state": script_state,
        "link_state": link_state,
        "note": note,
    }


def launcher_serves_this_app(script: Path) -> bool:
    """Whether a generated launcher was written to run this app's own host.

    A launcher that builds a command this build no longer accepts fails on every start
    with an argparse message in a log file nobody opens. The command is the
    discriminator: this app's launcher names the subcommand it runs through.
    """

    try:
        body = script.read_text(encoding="utf-8")
    except OSError:
        return False
    return SERVE_COMMAND in body


def ui_launcher_state(project_root: Path, portable_root: Path) -> dict[str, Any]:
    """Report the launcher and its link without changing anything."""

    script = launcher_path(portable_root)
    link = link_path(project_root)
    link_state = _link_state(link)
    if link_state == "linked" and not script.is_file():
        link_state = "broken_link"
    present = script.is_file()
    return {
        "script_path": str(script),
        "script_present": present,
        "serves_this_app": launcher_serves_this_app(script) if present else None,
        "link_path": str(link),
        "link_target": LINK_TARGET,
        "link_state": link_state,
        "default_port": DEFAULT_UI_PORT,
        "note": (
            "The launcher starts the app for this project and stops "
            "what it started with --stop. It is machine-local; keep it out of "
            "version control. It takes --open, --stop, and --port."
        ),
    }


def start_app(
    config: ResearchConfig,
    *,
    port: int | None = None,
    open_browser: bool = False,
) -> dict[str, Any]:
    """The app up for this project, and what it did.

    The launcher starts it rather than this module, because it already owns the
    free-port choice, the lock making that choice exclusive, the pid and port files,
    and the log.

    An app already up is left alone. Two apps on one project would each hold the
    project lock and open a gateway.
    """
    from .config import CLI_COMMAND, ConfigurationError

    script = launcher_path(config.portable_root)
    if not script.is_file():
        raise ConfigurationError(
            f"This project has no app launcher at {script}. "
            f"Run '{CLI_COMMAND} init' once to generate it."
        )
    if not launcher_serves_this_app(script):
        raise ConfigurationError(
            f"The generated launcher at {script} was written by an older build and "
            "runs a command this one no longer accepts, so it was not started. "
            f"Delete it and run '{CLI_COMMAND} start' again to write a current one; "
            "the file is machine-local and holds nothing of yours."
        )
    state = ui_launcher_state(config.project_root, config.portable_root)
    pid = _running_pid(config)
    if pid is not None:
        return {
            "running": True,
            "started": False,
            "pid": pid,
            "port": _recorded_port(config),
            "url": (
                f"http://127.0.0.1:{_recorded_port(config)}"
                if _recorded_port(config) is not None
                else None
            ),
        }
    command = [str(script)]
    if open_browser:
        command.append("--open")
    if port is not None:
        command.extend(["--port", str(port)])
    completed = subprocess.run(command, capture_output=True, text=True, check=False)
    return {
        "running": completed.returncode == 0,
        "started": completed.returncode == 0,
        "returncode": completed.returncode,
        "stdout": completed.stdout.strip(),
        "stderr": completed.stderr.strip(),
        "log": str(config.state_root / "logs" / "research-rag-ui.log"),
        "script": str(script),
        "link_state": state["link_state"],
    }


def stop_app(config: ResearchConfig) -> dict[str, Any]:
    """Stop the app and everything it started, and report what answered."""

    script = launcher_path(config.portable_root)
    if not script.is_file():
        return {"running": False, "stopped": False, "note": "No launcher to stop."}
    completed = subprocess.run(
        [str(script), "--stop"], capture_output=True, text=True, check=False
    )
    return {
        "running": _running_pid(config) is not None,
        "stopped": completed.returncode == 0,
        "returncode": completed.returncode,
        "stdout": completed.stdout.strip(),
        "stderr": completed.stderr.strip(),
    }


def _recorded_port(config: ResearchConfig) -> int | None:
    try:
        return int(
            (config.state_root / "research-rag-ui.port")
            .read_text(encoding="utf-8")
            .strip()
        )
    except (OSError, ValueError):
        return None


def _running_pid(config: ResearchConfig) -> int | None:
    """The pid the launcher recorded while that process is still alive.

    A pid file outlives its process, so the number alone is not a running app. The
    same check the launcher's own stop path uses decides it here.
    """

    try:
        pid = int(
            (config.state_root / "research-rag-ui.pid")
            .read_text(encoding="utf-8")
            .strip()
        )
    except (OSError, ValueError):
        return None
    return pid if _process_exists(pid) else None


def _process_exists(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True
